/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl.commonViews;

import etl.constants.StringConstants;
import etl.views.Extract;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.view.ModelMethodSelection;

/**
 *
 * @author Chinthaka Suren
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        setWindowIcon(); 
    }

    /*
    * @Method setWindowIcon 
    * Set Window Icon
    */
    private void setWindowIcon(){
        //Set ImageIcon of window
        ImageIcon img = new ImageIcon(StringConstants.ICON_FILE_PATH);
        setIconImage(img.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modelBtn = new javax.swing.JButton();
        etlToolBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emp-Sense Home (IT Industry)");
        setResizable(false);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 10, 150, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setText("Predict Your Employees' Churn");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 120, 330, 30);

        modelBtn.setBackground(new java.awt.Color(255, 255, 255));
        modelBtn.setForeground(new java.awt.Color(0, 0, 204));
        modelBtn.setText("Predict Employee Churn");
        modelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelBtnActionPerformed(evt);
            }
        });
        jPanel2.add(modelBtn);
        modelBtn.setBounds(197, 190, 170, 30);

        etlToolBtn.setBackground(new java.awt.Color(255, 255, 255));
        etlToolBtn.setForeground(new java.awt.Color(0, 0, 204));
        etlToolBtn.setText("ETL Tool");
        etlToolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etlToolBtnActionPerformed(evt);
            }
        });
        jPanel2.add(etlToolBtn);
        etlToolBtn.setBounds(70, 190, 120, 30);

        dashboardBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 204));
        dashboardBtn.setText("View Employee Churn");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dashboardBtn);
        dashboardBtn.setBounds(370, 190, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 180, 470, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 110, 470, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/background.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * @Method etlToolBtnActionPerformed 
    * Display ETL Tool
    * @param  ActionEvent
    */
    private void etlToolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etlToolBtnActionPerformed
        dispose();
        new Extract().setVisible(true);
    }//GEN-LAST:event_etlToolBtnActionPerformed

    /*
    * @Method modelBtnActionPerformed 
    * Display Model Train window
    * @param  ActionEvent
    */
    private void modelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelBtnActionPerformed
        dispose();
        new ModelMethodSelection().setVisible(true);
    }//GEN-LAST:event_modelBtnActionPerformed

    /*
    * @Method dashboardBtnActionPerformed 
    * Display Dashboard in web browser
    * @param  ActionEvent
    */
    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        try {
            openWebpage(new URI(StringConstants.DASHBOARD_URL));
        } catch (URISyntaxException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dashboardBtnActionPerformed

    /*
    * @Method openWebpage 
    * Open URL in web browser
    * @param  URI
    */
    public void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, StringConstants.DASHBOARD_NOT_AVAIL,
                    StringConstants.DASHBOARD_ERROR, JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton etlToolBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modelBtn;
    // End of variables declaration//GEN-END:variables
}
