/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl.commonViews;

import etl.constants.NumberConstants;
import etl.constants.StringConstants;
import etl.db.DBAccess;
import etl.views.Extract;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.TextField;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author suren
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */      
    private DBAccess dbAccess;
    private BufferedImage image;
    public Login() {
        initComponents();
        setWindowIcon();
        usernameTxt.setBackground(new Color(0, 0, 0, 0));
        passwordTxt.setBackground(new Color(0, 0, 0, 0));
        logoLabel.setBackground(new Color(0, 0, 0, 0));
        dbAccess = new DBAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("Username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emp-Sense - Login (IT Industry)");
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);

        jPanel2.setLayout(null);

        loginBtn.setBackground(new java.awt.Color(0, 0, 102));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 51, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/login_icon.png"))); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(null);
        loginBtn.setBorderPainted(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtn.setFocusPainted(false);
        loginBtn.setPreferredSize(new java.awt.Dimension(69, 23));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn);
        loginBtn.setBounds(180, 310, 200, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(180, 230, 200, 30);

        passwordTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordTxt.setOpaque(false);
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        jPanel2.add(passwordTxt);
        passwordTxt.setBounds(190, 230, 180, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(390, 230, 30, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 240, 80, 15);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(180, 190, 200, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/password_icon.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(390, 230, 30, 30);

        usernameTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernameTxt.setToolTipText("Username");
        usernameTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernameTxt.setOpaque(false);
        usernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTxtKeyReleased(evt);
            }
        });
        jPanel2.add(usernameTxt);
        usernameTxt.setBounds(190, 190, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 200, 70, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("WELCOME");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(210, 120, 109, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 110, 410, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 170, 410, 200);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/username_icon.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(390, 190, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(390, 190, 30, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forgot Password?");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 280, 120, 15);

        logoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/logo.png"))); // NOI18N
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setOpaque(true);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(logoLabel);
        logoLabel.setBounds(190, 20, 150, 80);

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFocusable(false);
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * @Method setWindowIcon 
    * Set Window Icon
    */
    private void setWindowIcon(){
        //Set ImageIcon of window
        ImageIcon img = new ImageIcon(StringConstants.ICON_FILE_PATH);
        setIconImage(img.getImage());
    }
    
    /*
    * @Method loginBtnActionPerformed 
    * Execute if user clicks on Login Button
    * Validate the empty fields
    * Check whether the username and the password(encrypted) exists
    * If user exists display Extract View with closing the current window
    * @param  Action Event
    */
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        LoginButtonAction();
    }//GEN-LAST:event_loginBtnActionPerformed

    /*
    * @Method usernameTxtKeyReleased 
    * Enable Enter Key login
    * @param  KeyEvent
    */
    private void usernameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTxtKeyReleased
        //Detect Enter Key pressed
        int keyCode = evt.getKeyCode();
        switch(keyCode){
            case KeyEvent.VK_ENTER:
                LoginButtonAction();
                break;           
        }
    }//GEN-LAST:event_usernameTxtKeyReleased

    /*
    * @Method passwordTxtKeyReleased 
    * Enable Enter Key login
    * @param  KeyEvent
    */
    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        //Detect Enter Key pressed
        int keyCode = evt.getKeyCode();
        switch(keyCode){
            case KeyEvent.VK_ENTER:
                LoginButtonAction();
                break;           
        }
    }//GEN-LAST:event_passwordTxtKeyReleased

    /*
    * @Method LoginButtonAction 
    * Check username and password matched and load next page
    */
    private void LoginButtonAction(){
        if(usernameTxt.getText().length() == NumberConstants.ZERO)  
            // Checking for empty field
            JOptionPane.showMessageDialog(null, 
                    StringConstants.EMPTY_FIELD,
                    StringConstants.ERROR,
                    JOptionPane.ERROR_MESSAGE);
        else if(passwordTxt.getPassword().length == NumberConstants.ZERO)  
            // Checking for empty field
            JOptionPane.showMessageDialog(null, 
                    StringConstants.EMPTY_FIELD,
                    StringConstants.ERROR,
                    JOptionPane.ERROR_MESSAGE);
        else{
            // Collecting the input
            String user = usernameTxt.getText();   
            char[] pass = passwordTxt.getPassword();
            // converting from array to string
            String pwd = String.copyValueOf(pass);  
            String encryptedPassword = StringConstants.EMPTY_STRING;
            try{
                // Create MessageDigest instance for MD5
                MessageDigest md = MessageDigest.getInstance(StringConstants.MD5_ENCRYPTION);
                //Add password bytes to digest
                md.update(pwd.getBytes());
                //Get the hash's bytes
                byte[] bytes = md.digest();
                //This bytes[] has bytes in decimal format;
                //Convert it to hexadecimal format
                StringBuilder sb = new StringBuilder();
                for(int i = NumberConstants.ZERO; i< bytes.length ;i++)
                {
                    sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 
                            NumberConstants.SIXTEEN).substring(1));
                }
                //Get complete hashed password in hex format to string variable
                encryptedPassword = sb.toString();                
            }
            catch(NoSuchAlgorithmException e){
                System.out.println(StringConstants.NO_ENCRYPTION_ALGO);
            }
            
            if(dbAccess.isLoginValid(user,encryptedPassword)){
                dispose();
                new HomeView().setVisible(true);
            }               
            else{
                JOptionPane.showMessageDialog(null, 
                        StringConstants.INCORRECT_CREDENTIALS,
                        StringConstants.ERROR,
                        JOptionPane.ERROR_MESSAGE);
            }               
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
