/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl.views;

import etl.constants.StringConstants;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.DefaultComboBoxModel;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.util.PythonInterpreter;

/**
 *
 * @author suren
 */
public class AttributeMapper extends javax.swing.JFrame {

    /**
     * Creates new form AttributeMapper
     */
    private final String filePath;
    private final String fileType;
    private final String[] header;
    public AttributeMapper(String selectedFilePath, String selectedFileType, 
            String[] headers) {
        initComponents();
        this.filePath = selectedFilePath;   
        this.fileType = selectedFileType;
        this.header = headers;
        
        switch(fileType){
            case StringConstants.CSV_EXTENSION:                
                setComboboxModels();
                break;
            case StringConstants.XML_EXTENSION:
                setComboboxModels();
                break;
            case StringConstants.EXCEL_EXTENSION:
                
                break;
            case StringConstants.JSON_EXTENSION:
                setComboboxModels();
                break;
            case StringConstants.SQL_EXTENSION:
                break;
        }
    }
    
    private void setComboboxModels(){
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> model3 = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> model4 = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> model5 = new DefaultComboBoxModel<>(header);
        genderComBox.setModel(model1);
        MaritalStatComBox.setModel(model2);
        jobRoleComBox.setModel(model3);
        salaryComBox.setModel(model4);
        noOfLeavesComBox.setModel(model5);
    }
    
    public void pythonCodeExecute(){
        try{
 
        //String prg = "import sys\nprint int(sys.argv[1])+int(sys.argv[2])\n";
        //BufferedWriter out = new BufferedWriter(new FileWriter("test1.py"));
        //out.write(prg);
        //out.close();
        
        
        /*PythonInterpreter interpreter = new PythonInterpreter();
        interpreter.exec("import sys\nsys.path['/home/suren/Desktop/pythontest.py']\nimport pythontest");
        // execute a function that takes a string and returns a string
        PyObject someFunc = interpreter.get("drumhead_height");
        PyObject result = someFunc.__call__(new PyInteger(15),new PyInteger(15));
        String realResult = (String) result.__tojava__(String.class);
        System.out.println(realResult);*/
        
        /* working PythonInterpreter python = new PythonInterpreter();

        int number1 = 10;
        int number2 = 32;

        python.set("number1", new PyInteger(number1));
        python.set("number2", new PyInteger(number2));
        python.exec("number3 = number1+number2");
        PyObject number3 = python.get("number3");
        System.out.println("val : "+number3.toString());*/ 
        
        int number1 = 10;
        int number2 = 32;
        Process p = Runtime.getRuntime().exec("python src/etl/pythonCodes/test1.py "+number1+" "+number2);
        BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
        //int ret = new Integer(in.readLine()).intValue();
        System.out.println("value is : "+in.readLine());
        }catch(Exception e){ System.out.println(e.toString());}
        
        PythonInterpreter interp = new PythonInterpreter();
        interp.exec("nums = [1,2,3]");
        PyObject nums = interp.get("nums");
        System.out.println("nums: " + nums);
        System.out.println("nums is of type: " + nums.getClass());
        PythonInterpreter python = new PythonInterpreter();
        python.set("path", new PyString(filePath));
        python.exec("import numpy");
        //PyObject nums = python.get("my_data");
        System.out.println("Data: " + nums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attributeListPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genderComBox = new javax.swing.JComboBox<>();
        MaritalStatComBox = new javax.swing.JComboBox<>();
        jobRoleComBox = new javax.swing.JComboBox<>();
        salaryComBox = new javax.swing.JComboBox<>();
        noOfLeavesComBox = new javax.swing.JComboBox<>();
        doneBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attribute Mapper");

        jLabel1.setText("Gender");

        jLabel2.setText("Marital Status");

        jLabel3.setText("Salary");

        jLabel4.setText("Job Role");

        jLabel5.setText("No of Leaves");

        genderComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MaritalStatComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jobRoleComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salaryComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        noOfLeavesComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        doneBtn.setText("Done");

        javax.swing.GroupLayout attributeListPanelLayout = new javax.swing.GroupLayout(attributeListPanel);
        attributeListPanel.setLayout(attributeListPanelLayout);
        attributeListPanelLayout.setHorizontalGroup(
            attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributeListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doneBtn)
                    .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(genderComBox, 0, 196, Short.MAX_VALUE)
                        .addComponent(MaritalStatComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jobRoleComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salaryComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noOfLeavesComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attributeListPanelLayout.setVerticalGroup(
            attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributeListPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genderComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MaritalStatComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jobRoleComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salaryComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attributeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noOfLeavesComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doneBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MaritalStatComBox;
    private javax.swing.JPanel attributeListPanel;
    private javax.swing.JButton doneBtn;
    private javax.swing.JComboBox<String> genderComBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jobRoleComBox;
    private javax.swing.JComboBox<String> noOfLeavesComBox;
    private javax.swing.JComboBox<String> salaryComBox;
    // End of variables declaration//GEN-END:variables
}
