/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl.views;

import etl.commonViews.HomeView;
import etl.constants.NumberConstants;
import etl.constants.StringConstants;
import etl.dictionary.SynonymDictionary;
import etl.models.attribute;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author suren
 */
public class AttributeMapper_Predict extends javax.swing.JFrame {

    /**
     * Creates new form AttributeMapper
     */
    //All declared variables
    private final String filePath;
    private final String[] header;
    private List<attribute> attributes;
    public AttributeMapper_Predict(String selectedFilePath,  
            String[] headers) {
        initComponents();
        
        setWindowIcon();
                
        this.filePath = selectedFilePath;
        this.header = headers;                
        setComboboxModels();   
    }
    
    /*
    * @Method setComboboxModels 
    * Set Combobox for attribtes to map them
    */
    private void setComboboxModels(){
        DefaultComboBoxModel<String> modelEmployeeID 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelEmployeeName 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelAge 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelGender 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelMaritalStatus 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelHavingDegree 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelJobRole 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelTenure 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelSalary 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelNoOfLeaves 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelDistance 
                = new DefaultComboBoxModel<>(header);
        DefaultComboBoxModel<String> modelNoOfDep 
                = new DefaultComboBoxModel<>(header);
        
        employeeIDComBox.setModel(modelEmployeeID);
        employeeNameComBox.setModel(modelEmployeeName);
        ageComBox.setModel(modelAge);
        genderComBox.setModel(modelGender);
        maritalStatComBox.setModel(modelMaritalStatus);
        havingDegreeComBox.setModel(modelHavingDegree);
        jobRoleComBox.setModel(modelJobRole);
        tenureComBox.setModel(modelTenure);
        salaryComBox.setModel(modelSalary);
        noOfLeavesComBox.setModel(modelNoOfLeaves);
        distanceComBox.setModel(modelDistance);
        noOfDepComBox.setModel(modelNoOfDep);
        
        SynonymDictionary dictionary = new SynonymDictionary();
        
        //Automate dropdown selection
        employeeIDComBox.setSelectedIndex(dictionary.getIndex(StringConstants.EMPLOYEE_ID, header));
        employeeNameComBox.setSelectedIndex(dictionary.getIndex(StringConstants.EMPLOYEE_NAME, header));
        ageComBox.setSelectedIndex(dictionary.getIndex(StringConstants.AGE, header));
        genderComBox.setSelectedIndex(dictionary.getIndex(StringConstants.GENDER, header));
        maritalStatComBox.setSelectedIndex(dictionary.getIndex(StringConstants.MARITAL_STAT, header));
        havingDegreeComBox.setSelectedIndex(dictionary.getIndex(StringConstants.HAVING_DEGREE, header));
        jobRoleComBox.setSelectedIndex(dictionary.getIndex(StringConstants.JOB_ROLE, header));
        tenureComBox.setSelectedIndex(dictionary.getIndex(StringConstants.TENURE, header));
        salaryComBox.setSelectedIndex(dictionary.getIndex(StringConstants.SALARY, header));
        noOfLeavesComBox.setSelectedIndex(dictionary.getIndex(StringConstants.NO_OF_LEAVES, header));
        distanceComBox.setSelectedIndex(dictionary.getIndex(StringConstants.DISTANCE, header));
        noOfDepComBox.setSelectedIndex(dictionary.getIndex(StringConstants.NO_OF_DEPENDENTS, header));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeIDComBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ageComBox = new javax.swing.JComboBox<>();
        employeeNameComBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        genderComBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maritalStatComBox = new javax.swing.JComboBox<>();
        jobRoleComBox = new javax.swing.JComboBox<>();
        salaryComBox = new javax.swing.JComboBox<>();
        noOfLeavesComBox = new javax.swing.JComboBox<>();
        defineRulesBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        distanceComBox = new javax.swing.JComboBox<>();
        noOfDepComBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        havingDegreeComBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tenureComBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmpSense - Attribute Mapper (IT Industry)");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        employeeIDComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(employeeIDComBox);
        employeeIDComBox.setBounds(130, 140, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Employee ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 110, 76, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Age");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 150, 36, 15);

        ageComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ageComBox);
        ageComBox.setBounds(130, 100, 220, 30);

        employeeNameComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(employeeNameComBox);
        employeeNameComBox.setBounds(490, 100, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Employee Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 110, 95, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Gender");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 150, 43, 15);

        genderComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(genderComBox);
        genderComBox.setBounds(490, 140, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Marital Status");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 190, 87, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Salary");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 270, 37, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Job Role");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 230, 53, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("No of Leaves");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 270, 78, 15);

        maritalStatComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(maritalStatComBox);
        maritalStatComBox.setBounds(130, 180, 220, 30);

        jobRoleComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jobRoleComBox);
        jobRoleComBox.setBounds(130, 220, 220, 30);

        salaryComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(salaryComBox);
        salaryComBox.setBounds(130, 260, 220, 30);

        noOfLeavesComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(noOfLeavesComBox);
        noOfLeavesComBox.setBounds(490, 260, 220, 30);

        defineRulesBtn.setBackground(new java.awt.Color(255, 255, 255));
        defineRulesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        defineRulesBtn.setForeground(new java.awt.Color(0, 51, 255));
        defineRulesBtn.setText("Define Rules");
        defineRulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defineRulesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(defineRulesBtn);
        defineRulesBtn.setBounds(550, 370, 157, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Distance");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 310, 52, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("No of Dependents");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 310, 111, 15);

        distanceComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(distanceComBox);
        distanceComBox.setBounds(130, 300, 220, 30);

        noOfDepComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(noOfDepComBox);
        noOfDepComBox.setBounds(490, 300, 220, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Having Degree");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 190, 89, 15);

        havingDegreeComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(havingDegreeComBox);
        havingDegreeComBox.setBounds(490, 180, 220, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tenure");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 230, 42, 15);

        tenureComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(tenureComBox);
        tenureComBox.setBounds(490, 220, 220, 30);

        jLabel10.setBackground(new java.awt.Color(51, 102, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 360, 710, 50);

        jLabel16.setBackground(new java.awt.Color(51, 102, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Map Attributes with Dataset");
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 20, 710, 50);

        jLabel15.setBackground(new java.awt.Color(51, 102, 255));
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 80, 710, 270);

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 750, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * @Method setWindowIcon 
    * Set Window Icon
    */
    private void setWindowIcon(){
        //Set ImageIcon of window
        ImageIcon img = new ImageIcon(StringConstants.ICON_FILE_PATH);
        setIconImage(img.getImage());
    }
    
    /*
    * @Method defineRulesBtnActionPerformed
    * Get mapped attribtes and pass them to the DefineRules window
    * @param  Action Event
    */
    private void defineRulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defineRulesBtnActionPerformed
        //set mapped attribute with defined attribute
        //Add attributes - *To add new attribute
        attributes = new ArrayList<>();
        String[] mappedAttributes = new String[]{
            employeeIDComBox.getSelectedItem().toString(), 
            employeeNameComBox.getSelectedItem().toString(),
            ageComBox.getSelectedItem().toString(),
            genderComBox.getSelectedItem().toString(),
            maritalStatComBox.getSelectedItem().toString(),
            havingDegreeComBox.getSelectedItem().toString(),            
            jobRoleComBox.getSelectedItem().toString(),
            tenureComBox.getSelectedItem().toString(),
            salaryComBox.getSelectedItem().toString(),
            noOfLeavesComBox.getSelectedItem().toString(),
            distanceComBox.getSelectedItem().toString(),
            noOfDepComBox.getSelectedItem().toString()
        };
        for (int i = NumberConstants.ZERO; 
                i < StringConstants.ATTRIBUTES.length-NumberConstants.ONE ; i++){
            String attr = StringConstants.ATTRIBUTES[i];
            attribute attribute = new attribute(attr);
            attribute.setRules(StringConstants.RULES_LIST.get(attr));
            attribute.setMatchingField(mappedAttributes[i]);
            attributes.add(attribute);
        }        
        
        dispose();
        new DefineRules(attributes, filePath, NumberConstants.PREDICT_DATA).setVisible(true);
    }//GEN-LAST:event_defineRulesBtnActionPerformed

    /*
    * @Method formWindowClosing 
    * Prevent closing system and display home page
    * @param  WindowEvent
    */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        if (JOptionPane.showConfirmDialog(this, 
            StringConstants.CLOSE_WINDOW_QUESTION, StringConstants.CLOSE_WINDOW, 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                dispose();
                new HomeView().setVisible(true);
        } 
    }//GEN-LAST:event_formWindowClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageComBox;
    private javax.swing.JButton defineRulesBtn;
    private javax.swing.JComboBox<String> distanceComBox;
    private javax.swing.JComboBox<String> employeeIDComBox;
    private javax.swing.JComboBox<String> employeeNameComBox;
    private javax.swing.JComboBox<String> genderComBox;
    private javax.swing.JComboBox<String> havingDegreeComBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jobRoleComBox;
    private javax.swing.JComboBox<String> maritalStatComBox;
    private javax.swing.JComboBox<String> noOfDepComBox;
    private javax.swing.JComboBox<String> noOfLeavesComBox;
    private javax.swing.JComboBox<String> salaryComBox;
    private javax.swing.JComboBox<String> tenureComBox;
    // End of variables declaration//GEN-END:variables
}
