/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etl.views;

import etl.constants.StringConstants;
import etl.readers.ReadCSV;
import etl.readers.ReadExcel;
import etl.readers.ReadJSON;
import etl.readers.ReadXML;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suren
 */
public class DataView extends javax.swing.JFrame {

    /**
     * Creates new form DataView
     */
    //All declared variables
    private String filePath;
    private String fileType;
    
    //Readers
    private ReadCSV csvReader;
    private ReadXML xmlReader;
    private ReadJSON jsonReader;
    
    private String[] headers;
    public DataView(String selectedFilePath, String selectedFileType) {
        initComponents();
        
        setWindowIcon();
                
        this.filePath = selectedFilePath;   
        this.fileType = selectedFileType;
        
        switch(fileType){
            case StringConstants.CSV_EXTENSION:
                csvReader = new ReadCSV();
                ReadCSV.selectedFilePath = filePath;
                ReadCSV.tableView = dataTableView;
                ReadCSV.jLableProgress = progressLable;
                ReadCSV.extractBtn = mapAttrBtn;                
                csvReader.start();
                break;
            case StringConstants.XML_EXTENSION:
                xmlReader = new ReadXML();
                ReadXML.selectedFilePath = filePath;
                ReadXML.tableView = dataTableView;
                ReadXML.jLableProgress = progressLable;
                ReadXML.extractBtn = mapAttrBtn;
                xmlReader.start();
                //xmlRead();
                break;
            case StringConstants.EXCEL_EXTENSION:
                ReadExcel excelReader = new ReadExcel();
                DefaultTableModel excelModel = 
                        excelReader.readExcelFrom(filePath); 
                dataTableView.setModel(excelModel);
                break;
            case StringConstants.JSON_EXTENSION:
                jsonReader = new ReadJSON();
                ReadJSON.selectedFilePath = filePath;
                ReadJSON.tableView = dataTableView;
                ReadJSON.jLableProgress = progressLable;
                ReadJSON.extractBtn = mapAttrBtn;
                jsonReader.start();
                break;
            case StringConstants.SQL_EXTENSION:
                break;
        }      
    }  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mapAttrBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTableView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        progressLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmpSense - Data View (IT Industry)");

        mapAttrBtn.setText("Map Attributes");
        mapAttrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapAttrBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setDoubleBuffered(true);

        dataTableView.setAutoCreateRowSorter(true);
        dataTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTableView.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dataTableView.setDragEnabled(true);
        dataTableView.setEnabled(false);
        dataTableView.setName(""); // NOI18N
        dataTableView.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(dataTableView);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("View of Selected Data");

        progressLable.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        progressLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/progress.gif"))); // NOI18N
        progressLable.setText("Loading Table......");
        progressLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(progressLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 500, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mapAttrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressLable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(mapAttrBtn)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * @Method setWindowIcon 
    * Set Window Icon
    */
    private void setWindowIcon(){
        //Set ImageIcon of window
        ImageIcon img = new ImageIcon(StringConstants.ICON_FILE_PATH);
        setIconImage(img.getImage());
    }
    
    /*
    * @Method extractBtnActionPerformed 
    * Get selected attribtes and send them to next window : AttributeMapper
    * @param  ActionEvent
    */
    private void mapAttrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapAttrBtnActionPerformed
        //To get headers string array to bind in jcombobox
        switch(fileType){
            case StringConstants.CSV_EXTENSION:                
                headers = csvReader.getCheckBoxes();
                //addCheckBox();
                break;
            case StringConstants.XML_EXTENSION:
                headers = xmlReader.getHeaders();
                //addCheckBox();
                break;
            case StringConstants.EXCEL_EXTENSION:
                
                break;
            case StringConstants.JSON_EXTENSION:
                headers = jsonReader.getHeaders();
                break;
            case StringConstants.SQL_EXTENSION:
                break;
        }
        dispose();
        new AttributeMapper(filePath,fileType,headers).setVisible(true);       
    }//GEN-LAST:event_mapAttrBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTableView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mapAttrBtn;
    private javax.swing.JLabel progressLable;
    // End of variables declaration//GEN-END:variables
}
