/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import etl.commonViews.HomeView;
import etl.constants.StringConstants;
import etl.controllers.CustomConfirmDialog;
import etl.db.DBAccess;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author suren
 */
public class ModelMethodSelection extends javax.swing.JFrame {

    /**
     * Creates new form ModelMethodSelection
     */
    private DBAccess dbAccess;
    public ModelMethodSelection() {
        initComponents();
        setWindowIcon();
        dbAccess = new DBAccess();
    }

    /*
    * @Method setWindowIcon 
    * Set Window Icon
    */
    private void setWindowIcon(){
        //Set ImageIcon of window
        ImageIcon img = new ImageIcon(StringConstants.ICON_FILE_PATH);
        setIconImage(img.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeSelect = new javax.swing.ButtonGroup();
        trainPredictSelect = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tuneCheckbox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        autoRadioBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        manualRadioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        trainRadioBtn = new javax.swing.JRadioButton();
        predictRadioBtn = new javax.swing.JRadioButton();
        applyBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select the Mode");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Method Selection");
        jLabel1.setOpaque(true);
        jPanel5.add(jLabel1);
        jLabel1.setBounds(20, 10, 370, 39);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        tuneCheckbox.setBackground(new java.awt.Color(51, 102, 255));
        tuneCheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tuneCheckbox.setText("Increase Accuracy");
        tuneCheckbox.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>Check to increase the accuracy <b> ONLY </b> to train the <br> algorithm. (This process might take several minutes)</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tuneCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tuneCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3);
        jPanel3.setBounds(20, 260, 370, 72);

        autoRadioBtn.setBackground(new java.awt.Color(51, 102, 255));
        modeSelect.add(autoRadioBtn);
        autoRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        autoRadioBtn.setSelected(true);
        autoRadioBtn.setText("Automatically Select the Best Algorithm");
        jPanel5.add(autoRadioBtn);
        autoRadioBtn.setBounds(70, 70, 271, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>The best algorithm will be selected automatically for the prediction based on the efficiency</html>");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(90, 90, 255, 50);

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setOpaque(true);
        jPanel5.add(jLabel7);
        jLabel7.setBounds(30, 60, 350, 90);

        manualRadioBtn.setBackground(new java.awt.Color(51, 102, 255));
        modeSelect.add(manualRadioBtn);
        manualRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manualRadioBtn.setText("Manually Select the Algorithm");
        jPanel5.add(manualRadioBtn);
        manualRadioBtn.setBounds(70, 170, 211, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Select the algorithm you prefer (K-Nearest Neighbours, Random Forest, Support Vector Machine)</html>");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(90, 190, 280, 50);

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(30, 160, 350, 90);

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setLayout(null);

        trainRadioBtn.setBackground(new java.awt.Color(51, 102, 255));
        trainPredictSelect.add(trainRadioBtn);
        trainRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trainRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        trainRadioBtn.setSelected(true);
        trainRadioBtn.setText("Train");
        trainRadioBtn.setOpaque(false);
        jPanel6.add(trainRadioBtn);
        trainRadioBtn.setBounds(60, 20, 61, 25);

        predictRadioBtn.setBackground(new java.awt.Color(51, 102, 255));
        trainPredictSelect.add(predictRadioBtn);
        predictRadioBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        predictRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        predictRadioBtn.setText("Predict");
        predictRadioBtn.setOpaque(false);
        jPanel6.add(predictRadioBtn);
        predictRadioBtn.setBounds(140, 20, 73, 25);

        applyBtn.setBackground(new java.awt.Color(255, 255, 255));
        applyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        applyBtn.setForeground(new java.awt.Color(0, 51, 255));
        applyBtn.setText("Apply");
        applyBtn.setMargin(new java.awt.Insets(3, 14, 3, 14));
        applyBtn.setPreferredSize(new java.awt.Dimension(67, 28));
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });
        jPanel6.add(applyBtn);
        applyBtn.setBounds(262, 9, 98, 40);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etl/images/bg_2.png"))); // NOI18N
        jPanel6.add(jLabel8);
        jLabel8.setBounds(30, 10, 210, 40);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 340, 370, 60);

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        if(tuneCheckbox.isSelected()){
            dbAccess.deleteTuningData();
            dbAccess.insertTuningData(true);
        }
        else{
            dbAccess.deleteTuningData();
            dbAccess.insertTuningData(false);
        }
        
        if(autoRadioBtn.isSelected()){
            String path = "D:/SLIIT/SoftwareIndustry";
            Process p;
            if(trainRadioBtn.isSelected()){
                try {
                    p = Runtime.getRuntime().exec("cmd /c start /wait " + path + "/Automation_Train.py");
                    int i = p.waitFor();
                    System.out.println(i);
                    JOptionPane.showMessageDialog(null, "Done!! database updated!!");
                } catch (IOException | InterruptedException ex) {
                    Logger.getLogger(AlgorithmSelectionTrain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(predictRadioBtn.isSelected()){
                try {
                    p = Runtime.getRuntime().exec("cmd /c start /wait " + path + "/Automation_Predict.py");
                    int i = p.waitFor();
                    System.out.println(i);
                    JOptionPane.showMessageDialog(null, "Done!! database updated!!");
                } catch (IOException | InterruptedException ex) {
                    Logger.getLogger(AlgorithmSelectionTrain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else if(manualRadioBtn.isSelected()){
            if(trainRadioBtn.isSelected()){
                String path = "D:/SLIIT/SoftwareIndustry";
                Process p;
                try {
                    p = Runtime.getRuntime().exec("cmd /c start /wait " + path + "/Accuracy_IT.py");
                    int i = p.waitFor();
                    System.out.println(i);
                } catch (IOException ex) {
                    Logger.getLogger(AlgorithmSelectionTrain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(AlgorithmSelectionTrain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                new AlgorithmSelectionTrain().setVisible(true);
                dispose();
            }
            else if(predictRadioBtn.isSelected()){
                new AlgorithmSelectionPredict().setVisible(true);
                dispose();
            }
            
        }
    }//GEN-LAST:event_applyBtnActionPerformed

    /*
    * @Method formWindowClosing 
    * Prevent closing system and display home page
    * @param  WindowEvent
    */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        /*if (JOptionPane.showConfirmDialog(this, 
            StringConstants.CLOSE_WINDOW_QUESTION, StringConstants.CLOSE_WINDOW, 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                dispose();
                new HomeView().setVisible(true);
        } */
        CustomConfirmDialog dialog = new CustomConfirmDialog(this, new HomeView(), 
                StringConstants.CLOSE_WINDOW, StringConstants.CLOSE_WINDOW_QUESTION);
        // set the size of the window
        dialog.setSize(300, 150);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModelMethodSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModelMethodSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModelMethodSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModelMethodSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModelMethodSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyBtn;
    private javax.swing.JRadioButton autoRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton manualRadioBtn;
    private javax.swing.ButtonGroup modeSelect;
    private javax.swing.JRadioButton predictRadioBtn;
    private javax.swing.ButtonGroup trainPredictSelect;
    private javax.swing.JRadioButton trainRadioBtn;
    private javax.swing.JCheckBox tuneCheckbox;
    // End of variables declaration//GEN-END:variables
}
